name: Audit live site
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: lighthouse-compare
      uses: mdsadiq/lighthouse-compare@v1.2.0
      with:
        url: 'https://tatacliq.com'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
