name: Audit live site
on: push
jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: https://tatacliq.com
          uploadArtifacts: true # Upload the report as an artifact
          temporaryPublicStorage: true # Store the report publicly for a short time
