name: Audit live site
on: push
jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          lhciServerURL: https://www.tatacliq.com/power-by-bata-mens-power-aw-blue-walking-shoes/p-mp000000022283744
          githubToken: ${{ secrets.GITHUB_TOKEN  }}
          urls: https://www.tatacliq.com/power-by-bata-mens-power-aw-blue-walking-shoes/p-mp000000022283744
          temporaryPublicStorage: true # Store the report publicly for a short time
      
