name: Run Every 1 Minutes

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Print a message
      - name: Print a message
        run: echo "This job runs every 8:30 pm  minutes!"
